import type { Card } from "@/lib/types";

// Starter deck. Every card is Python syntax the user can fumble under pressure.
// Blanks in `code` are marked with ___ for fill cards. Keep prompts terse and
// answers exact-ish; explanations one line, problems-first.
//
// This is the seed set (build order step 3 / expanded in step 9). Content is
// plain data so it can later be generated or imported without touching UI.

const STARTER: Card[] = [
  // ---------------- Arrays & Hashing ----------------
  {
    id: "ah-dict-get-default",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "dict.get",
    type: "fill",
    prompt: "Read key 'k' from dict d, defaulting to 0 if absent.",
    code: "count = d.___('k', 0)",
    answer: "get",
    explanation: "dict.get(key, default) returns default instead of raising KeyError.",
    difficulty: 1,
    tags: ["dict"],
  },
  {
    id: "ah-defaultdict-list",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "defaultdict",
    type: "fill",
    prompt: "Create a dict whose missing values start as an empty list.",
    code: "from collections import defaultdict\ngroups = defaultdict(___)",
    answer: "list",
    explanation: "Pass the factory (list) — not list() — so each missing key gets a fresh [].",
    difficulty: 1,
    tags: ["defaultdict", "collections"],
  },
  {
    id: "ah-counter-most-common",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "Counter",
    type: "mcq",
    prompt: "Which returns the 2 most frequent elements of nums as (val, count) pairs?",
    answer: "b",
    options: [
      { id: "a", text: "Counter(nums).top(2)" },
      { id: "b", text: "Counter(nums).most_common(2)" },
      { id: "c", text: "Counter(nums).common(2)" },
      { id: "d", text: "Counter(nums)[:2]" },
    ],
    explanation: "Counter.most_common(k) returns the k highest-count pairs, most frequent first.",
    difficulty: 1,
    tags: ["Counter", "collections"],
  },
  {
    id: "ah-set-literal",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "set",
    type: "mcq",
    prompt: "How do you create an EMPTY set?",
    answer: "c",
    options: [
      { id: "a", text: "{}" },
      { id: "b", text: "[]" },
      { id: "c", text: "set()" },
      { id: "d", text: "()" },
    ],
    explanation: "{} is an empty dict; set() is the empty set.",
    difficulty: 1,
    tags: ["set"],
  },
  {
    id: "ah-enumerate-start",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "enumerate",
    type: "fill",
    prompt: "Loop over nums with a 1-based index.",
    code: "for i, x in ___(nums, 1):\n    ...",
    answer: "enumerate",
    explanation: "enumerate(iterable, start) yields (index, value); start sets the first index.",
    difficulty: 1,
    tags: ["enumerate"],
  },
  {
    id: "ah-comprehension-filter",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "comprehensions",
    type: "fill",
    prompt: "List comprehension of squares of even numbers in nums.",
    code: "sq = [x*x for x in nums ___ x % 2 == 0]",
    answer: "if",
    explanation: "The filter clause goes after the loop: [expr for x in it if cond].",
    difficulty: 2,
    tags: ["comprehensions"],
  },
  {
    id: "ah-dict-comprehension",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "comprehensions",
    type: "fill",
    prompt: "Build {value: index} from nums via comprehension.",
    code: "idx = {v: i for i, v in ___(nums)}",
    answer: "enumerate",
    explanation: "Dict comprehension with enumerate maps each value to its position.",
    difficulty: 2,
    tags: ["comprehensions", "dict"],
  },
  {
    id: "ah-frequency-loop",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "defaultdict",
    type: "mcq",
    prompt: "count is a defaultdict(int). How do you tally x?",
    answer: "a",
    options: [
      { id: "a", text: "count[x] += 1" },
      { id: "b", text: "count.add(x)" },
      { id: "c", text: "count[x].append(1)" },
      { id: "d", text: "count.increment(x)" },
    ],
    explanation: "defaultdict(int) starts missing keys at 0, so += 1 just works.",
    difficulty: 1,
    tags: ["defaultdict"],
  },

  // ---------------- Slicing / strings ----------------
  {
    id: "str-reverse-slice",
    language: "python",
    topic: "Two Pointers",
    primitive: "slicing",
    type: "fill",
    prompt: "Reverse the string s with a slice.",
    code: "rev = s[___]",
    answer: "::-1",
    explanation: "s[::-1] steps backwards over the whole sequence.",
    difficulty: 1,
    tags: ["slicing", "string"],
  },
  {
    id: "str-join",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "str.join",
    type: "mcq",
    prompt: "Join a list of chars `ch` into a string.",
    answer: "b",
    options: [
      { id: "a", text: "ch.join('')" },
      { id: "b", text: "''.join(ch)" },
      { id: "c", text: "join(ch)" },
      { id: "d", text: "str(ch)" },
    ],
    explanation: "The separator string owns join: ''.join(iterable_of_strings).",
    difficulty: 1,
    tags: ["string", "join"],
  },
  {
    id: "str-isalnum",
    language: "python",
    topic: "Two Pointers",
    primitive: "str methods",
    type: "fill",
    prompt: "Check if character c is a letter or digit (for valid-palindrome filtering).",
    code: "if c.___():\n    ...",
    answer: "isalnum",
    explanation: "str.isalnum() is True for alphanumeric characters.",
    difficulty: 1,
    tags: ["string"],
  },
  {
    id: "slice-copy",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "slicing",
    type: "mcq",
    prompt: "Which makes a shallow COPY of list a?",
    answer: "a",
    options: [
      { id: "a", text: "a[:]" },
      { id: "b", text: "a" },
      { id: "c", text: "a.copy" },
      { id: "d", text: "&a" },
    ],
    explanation: "a[:] slices the whole list into a new list; a alone aliases it.",
    difficulty: 1,
    tags: ["slicing"],
  },

  // ---------------- Sorting ----------------
  {
    id: "sort-key-lambda",
    language: "python",
    topic: "Intervals",
    primitive: "sorted key",
    type: "fill",
    prompt: "Sort intervals by their start value (index 0).",
    code: "intervals.sort(key=lambda x: x[___])",
    answer: "0",
    explanation: "key extracts the sort field; x[0] is the interval start.",
    difficulty: 1,
    tags: ["sorting", "lambda"],
  },
  {
    id: "sort-reverse",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "sorted key",
    type: "mcq",
    prompt: "Sort nums in DESCENDING order into a new list.",
    answer: "c",
    options: [
      { id: "a", text: "sorted(nums).reverse()" },
      { id: "b", text: "nums.sort(desc=True)" },
      { id: "c", text: "sorted(nums, reverse=True)" },
      { id: "d", text: "reversed(sorted(nums))" },
    ],
    explanation: "sorted(..., reverse=True) returns a new descending list. list.reverse() returns None.",
    difficulty: 1,
    tags: ["sorting"],
  },
  {
    id: "sort-by-count",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "sorted key",
    type: "fill",
    prompt: "Sort keys of dict count by their value, highest first.",
    code: "order = sorted(count, key=count.get, ___=True)",
    answer: "reverse",
    explanation: "key=count.get looks up each key's value; reverse=True flips to descending.",
    difficulty: 2,
    tags: ["sorting"],
  },

  // ---------------- Heap ----------------
  {
    id: "heap-push",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "fill",
    prompt: "Push value v onto a min-heap list h.",
    code: "import heapq\nheapq.___(h, v)",
    answer: "heappush",
    explanation: "heapq.heappush(heap, item) maintains the min-heap invariant.",
    difficulty: 1,
    tags: ["heapq"],
  },
  {
    id: "heap-pop",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "mcq",
    prompt: "Which pops the SMALLEST element from heap h?",
    answer: "a",
    options: [
      { id: "a", text: "heapq.heappop(h)" },
      { id: "b", text: "h.pop(0)" },
      { id: "c", text: "heapq.pop(h)" },
      { id: "d", text: "heapq.heapmin(h)" },
    ],
    explanation: "heapq is a min-heap; heappop returns and removes the smallest item.",
    difficulty: 1,
    tags: ["heapq"],
  },
  {
    id: "heap-max",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "mcq",
    prompt: "How do you simulate a MAX-heap with heapq for integers?",
    answer: "b",
    options: [
      { id: "a", text: "heapq.heapmax(h, x)" },
      { id: "b", text: "push -x, then negate on pop" },
      { id: "c", text: "heapq.heappush(h, x, reverse=True)" },
      { id: "d", text: "use heapq.maxheapify(h)" },
    ],
    explanation: "heapq only does min-heaps; negate values to invert the ordering.",
    difficulty: 2,
    tags: ["heapq"],
  },
  {
    id: "heap-heapify",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "fill",
    prompt: "Turn list nums into a heap in-place, O(n).",
    code: "heapq.___(nums)",
    answer: "heapify",
    explanation: "heapq.heapify(list) reorders the list into a valid heap in linear time.",
    difficulty: 1,
    tags: ["heapq"],
  },

  // ---------------- Deque ----------------
  {
    id: "deque-init",
    language: "python",
    topic: "Graphs",
    primitive: "deque",
    type: "fill",
    prompt: "Create a queue for BFS seeded with the start node.",
    code: "from collections import deque\nq = ___([start])",
    answer: "deque",
    explanation: "deque gives O(1) popleft; a plain list's pop(0) is O(n).",
    difficulty: 1,
    tags: ["deque", "bfs"],
  },
  {
    id: "deque-popleft",
    language: "python",
    topic: "Graphs",
    primitive: "deque",
    type: "mcq",
    prompt: "Dequeue from the FRONT of a deque q in O(1).",
    answer: "a",
    options: [
      { id: "a", text: "q.popleft()" },
      { id: "b", text: "q.pop(0)" },
      { id: "c", text: "q.dequeue()" },
      { id: "d", text: "q.shift()" },
    ],
    explanation: "deque.popleft() removes from the left end in constant time.",
    difficulty: 1,
    tags: ["deque"],
  },

  // ---------------- Binary Search ----------------
  {
    id: "bisect-left",
    language: "python",
    topic: "Binary Search",
    primitive: "bisect",
    type: "fill",
    prompt: "Find the leftmost insertion index for x in sorted list a.",
    code: "import bisect\ni = bisect.___(a, x)",
    answer: "bisect_left",
    explanation: "bisect_left returns the first position where x could be inserted to keep a sorted.",
    difficulty: 2,
    tags: ["bisect"],
  },
  {
    id: "bs-mid",
    language: "python",
    topic: "Binary Search",
    primitive: "binary search",
    type: "fill",
    prompt: "Compute the midpoint of lo..hi without overflow concerns (Python).",
    code: "mid = (lo + hi) ___ 2",
    answer: "//",
    explanation: "// is floor division, keeping mid an integer index.",
    difficulty: 1,
    tags: ["binary-search"],
  },

  // ---------------- Trees / recursion ----------------
  {
    id: "tree-inorder",
    language: "python",
    topic: "Trees",
    primitive: "DFS",
    type: "mcq",
    prompt: "In-order DFS of a binary tree visits nodes in which order?",
    answer: "b",
    options: [
      { id: "a", text: "node, left, right" },
      { id: "b", text: "left, node, right" },
      { id: "c", text: "left, right, node" },
      { id: "d", text: "right, node, left" },
    ],
    explanation: "In-order = left subtree, current node, right subtree — sorted order for a BST.",
    difficulty: 2,
    tags: ["dfs", "tree"],
  },

  // ---------------- Comprehension / misc ----------------
  {
    id: "grid-init",
    language: "python",
    topic: "2-D DP",
    primitive: "comprehensions",
    type: "mcq",
    prompt: "Create an R×C grid of zeros WITHOUT aliasing rows.",
    answer: "c",
    options: [
      { id: "a", text: "[[0]*C]*R" },
      { id: "b", text: "[[0]*R]*C" },
      { id: "c", text: "[[0]*C for _ in range(R)]" },
      { id: "d", text: "[0]*C*R" },
    ],
    explanation: "[[0]*C]*R shares one row object; the comprehension makes R independent rows.",
    difficulty: 2,
    tags: ["comprehensions", "grid"],
  },
  {
    id: "inf-value",
    language: "python",
    topic: "1-D DP",
    primitive: "float inf",
    type: "fill",
    prompt: "Initialize a running minimum to positive infinity.",
    code: "best = float('___')",
    answer: "inf",
    explanation: "float('inf') is larger than any real number — a safe min seed.",
    difficulty: 1,
    tags: ["dp"],
  },
  {
    id: "zip-pairs",
    language: "python",
    topic: "Two Pointers",
    primitive: "zip",
    type: "fill",
    prompt: "Iterate over consecutive pairs (a[i], a[i+1]).",
    code: "for x, y in ___(a, a[1:]):\n    ...",
    answer: "zip",
    explanation: "zip(a, a[1:]) pairs each element with its successor.",
    difficulty: 2,
    tags: ["zip"],
  },
  {
    id: "divmod-use",
    language: "python",
    topic: "Math & Geometry",
    primitive: "divmod",
    type: "mcq",
    prompt: "What does divmod(17, 5) return?",
    answer: "a",
    options: [
      { id: "a", text: "(3, 2)" },
      { id: "b", text: "(2, 3)" },
      { id: "c", text: "3.4" },
      { id: "d", text: "(3, 5)" },
    ],
    explanation: "divmod(a, b) returns (a // b, a % b) — quotient then remainder.",
    difficulty: 1,
    tags: ["math"],
  },
  {
    id: "bit-count-set",
    language: "python",
    topic: "Bit Manipulation",
    primitive: "bit ops",
    type: "fill",
    prompt: "Count the set bits of integer n (Python 3.10+).",
    code: "ones = n.___()",
    answer: "bit_count",
    explanation: "int.bit_count() returns the number of 1s; bin(n).count('1') is the classic fallback.",
    difficulty: 2,
    tags: ["bit-manipulation"],
  },
  {
    id: "bit-lowest",
    language: "python",
    topic: "Bit Manipulation",
    primitive: "bit ops",
    type: "mcq",
    prompt: "Which expression isolates the lowest set bit of n?",
    answer: "b",
    options: [
      { id: "a", text: "n & (n - 1)" },
      { id: "b", text: "n & (-n)" },
      { id: "c", text: "n | (n - 1)" },
      { id: "d", text: "n ^ (n - 1)" },
    ],
    explanation: "n & -n keeps only the lowest set bit; n & (n-1) clears it instead.",
    difficulty: 3,
    tags: ["bit-manipulation"],
  },
];

// ------------------------------------------------------------------
// Expanded deck — full topic + primitive coverage (build order step 9).
// ------------------------------------------------------------------
const MORE: Card[] = [
  // ================= Strings / dicts / sets primitives =================
  {
    id: "str-split-ws",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "str.split",
    type: "fill",
    prompt: "Split a sentence into words on whitespace.",
    code: "words = sentence.___()",
    answer: "split",
    explanation: "str.split() with no args splits on any run of whitespace.",
    difficulty: 1,
    tags: ["string"],
  },
  {
    id: "str-ord-chr",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "ord/chr",
    type: "mcq",
    prompt: "How do you get the 0–25 alphabet index of a lowercase letter c?",
    answer: "b",
    options: [
      { id: "a", text: "int(c) - int('a')" },
      { id: "b", text: "ord(c) - ord('a')" },
      { id: "c", text: "c - 'a'" },
      { id: "d", text: "chr(c) - chr('a')" },
    ],
    explanation: "ord() gives the code point; subtract ord('a') for a 0-based index.",
    difficulty: 1,
    tags: ["string", "ord"],
  },
  {
    id: "dict-items-loop",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "dict.items",
    type: "fill",
    prompt: "Iterate over a dict's keys and values together.",
    code: "for k, v in d.___():\n    ...",
    answer: "items",
    explanation: "dict.items() yields (key, value) pairs.",
    difficulty: 1,
    tags: ["dict"],
  },
  {
    id: "dict-setdefault",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "dict.setdefault",
    type: "fill",
    prompt: "Append 5 to d['k'], creating an empty list first if needed (no defaultdict).",
    code: "d.___('k', []).append(5)",
    answer: "setdefault",
    explanation: "setdefault(key, default) returns the existing value or inserts the default.",
    difficulty: 2,
    tags: ["dict"],
  },
  {
    id: "set-add-prim",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "set",
    type: "fill",
    prompt: "Add x to a set `seen`.",
    code: "seen.___(x)",
    answer: "add",
    explanation: "set.add(x) inserts a single element; .update() adds many.",
    difficulty: 1,
    tags: ["set"],
  },
  {
    id: "set-intersection",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "set ops",
    type: "mcq",
    prompt: "Which gives elements common to sets a and b?",
    answer: "c",
    options: [
      { id: "a", text: "a + b" },
      { id: "b", text: "a | b" },
      { id: "c", text: "a & b" },
      { id: "d", text: "a - b" },
    ],
    explanation: "& is intersection; | is union; - is difference; ^ is symmetric difference.",
    difficulty: 1,
    tags: ["set"],
  },
  {
    id: "str-count-char",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "str.count",
    type: "fill",
    prompt: "Count how many times '1' appears in the binary string bits.",
    code: "ones = bits.___('1')",
    answer: "count",
    explanation: "str.count(sub) counts non-overlapping occurrences.",
    difficulty: 1,
    tags: ["string"],
  },
  {
    id: "list-append-vs-extend",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "list methods",
    type: "mcq",
    prompt: "a = [1,2]. After a.extend([3,4]), what is a?",
    answer: "a",
    options: [
      { id: "a", text: "[1, 2, 3, 4]" },
      { id: "b", text: "[1, 2, [3, 4]]" },
      { id: "c", text: "[[1,2],[3,4]]" },
      { id: "d", text: "[3, 4, 1, 2]" },
    ],
    explanation: "extend adds each element; append([3,4]) would nest the list.",
    difficulty: 1,
    tags: ["list"],
  },

  // ================= Two Pointers =================
  {
    id: "tp-converge-init",
    language: "python",
    topic: "Two Pointers",
    primitive: "two pointers",
    type: "fill",
    prompt: "Initialize converging pointers on list a.",
    code: "l, r = 0, ___ - 1",
    answer: "len(a)",
    explanation: "r starts at the last index, len(a) - 1; move l/r inward while l < r.",
    difficulty: 1,
    tags: ["two-pointers"],
  },
  {
    id: "tp-palindrome-loop",
    language: "python",
    topic: "Two Pointers",
    primitive: "two pointers",
    type: "mcq",
    prompt: "Loop condition for the converging palindrome check?",
    answer: "b",
    options: [
      { id: "a", text: "while l <= r" },
      { id: "b", text: "while l < r" },
      { id: "c", text: "while l != r" },
      { id: "d", text: "while r > 0" },
    ],
    explanation: "l < r stops when the pointers meet; the middle char needs no compare.",
    difficulty: 1,
    tags: ["two-pointers"],
  },
  {
    id: "tp-3sum-skip",
    language: "python",
    topic: "Two Pointers",
    primitive: "two pointers",
    type: "mcq",
    prompt: "In 3Sum, after finding a triplet, how do you skip duplicate left values?",
    answer: "a",
    options: [
      { id: "a", text: "while l < r and nums[l] == nums[l+1]: l += 1" },
      { id: "b", text: "l = r" },
      { id: "c", text: "continue" },
      { id: "d", text: "nums.remove(nums[l])" },
    ],
    explanation: "Advance past equal values so duplicate triplets aren't emitted.",
    difficulty: 3,
    tags: ["two-pointers"],
  },

  // ================= Sliding Window =================
  {
    id: "sw-window-len",
    language: "python",
    topic: "Sliding Window",
    primitive: "sliding window",
    type: "fill",
    prompt: "Length of the window between indices left and right (inclusive).",
    code: "length = right - left + ___",
    answer: "1",
    explanation: "Inclusive window length is right - left + 1.",
    difficulty: 1,
    tags: ["sliding-window"],
  },
  {
    id: "sw-counter-inc",
    language: "python",
    topic: "Sliding Window",
    primitive: "sliding window",
    type: "fill",
    prompt: "Add the incoming char c to a window Counter.",
    code: "window[c] ___ 1",
    answer: "+=",
    explanation: "Track the window's contents by incrementing counts as it grows.",
    difficulty: 1,
    tags: ["sliding-window", "Counter"],
  },
  {
    id: "sw-shrink",
    language: "python",
    topic: "Sliding Window",
    primitive: "sliding window",
    type: "mcq",
    prompt: "When a constraint is violated, how do you shrink the window?",
    answer: "b",
    options: [
      { id: "a", text: "right -= 1" },
      { id: "b", text: "remove s[left]; left += 1" },
      { id: "c", text: "left = right" },
      { id: "d", text: "window.clear()" },
    ],
    explanation: "Contract from the left: drop s[left]'s contribution, then advance left.",
    difficulty: 2,
    tags: ["sliding-window"],
  },
  {
    id: "sw-fixed",
    language: "python",
    topic: "Sliding Window",
    primitive: "sliding window",
    type: "mcq",
    prompt: "For a FIXED window of size k, when do you start removing the left element?",
    answer: "c",
    options: [
      { id: "a", text: "never" },
      { id: "b", text: "when right == 0" },
      { id: "c", text: "once the window exceeds size k" },
      { id: "d", text: "at the end" },
    ],
    explanation: "Add right, and once (right - left + 1) > k, drop the left element.",
    difficulty: 2,
    tags: ["sliding-window"],
  },

  // ================= Stack =================
  {
    id: "stack-push",
    language: "python",
    topic: "Stack",
    primitive: "stack",
    type: "fill",
    prompt: "Push x onto a list-based stack.",
    code: "stack.___(x)",
    answer: "append",
    explanation: "A list is a stack: append pushes, pop() pops the top.",
    difficulty: 1,
    tags: ["stack"],
  },
  {
    id: "stack-peek",
    language: "python",
    topic: "Stack",
    primitive: "stack",
    type: "mcq",
    prompt: "How do you peek at the top of a list-stack without removing it?",
    answer: "a",
    options: [
      { id: "a", text: "stack[-1]" },
      { id: "b", text: "stack[0]" },
      { id: "c", text: "stack.peek()" },
      { id: "d", text: "stack.top" },
    ],
    explanation: "The top of the stack is the last element, stack[-1].",
    difficulty: 1,
    tags: ["stack"],
  },
  {
    id: "stack-guard",
    language: "python",
    topic: "Stack",
    primitive: "stack",
    type: "fill",
    prompt: "Only pop while the stack is non-empty and the top exceeds h.",
    code: "while stack ___ stack[-1] > h:\n    stack.pop()",
    answer: "and",
    explanation: "Check `stack` truthiness first so `stack[-1]` never indexes an empty list.",
    difficulty: 2,
    tags: ["stack", "monotonic-stack"],
  },
  {
    id: "stack-paren-map",
    language: "python",
    topic: "Stack",
    primitive: "stack",
    type: "mcq",
    prompt: "Best structure to match closing to opening brackets?",
    answer: "b",
    options: [
      { id: "a", text: "a list of tuples" },
      { id: "b", text: "a dict {')':'(', ']':'[', '}':'{'}" },
      { id: "c", text: "a set of pairs" },
      { id: "d", text: "two parallel lists" },
    ],
    explanation: "A close→open dict lets you compare the popped top in O(1).",
    difficulty: 2,
    tags: ["stack"],
  },
  {
    id: "stack-pop-empty",
    language: "python",
    topic: "Stack",
    primitive: "stack",
    type: "mcq",
    prompt: "What happens on [].pop()?",
    answer: "c",
    options: [
      { id: "a", text: "returns None" },
      { id: "b", text: "returns 0" },
      { id: "c", text: "raises IndexError" },
      { id: "d", text: "returns []" },
    ],
    explanation: "Popping an empty list raises IndexError — guard with `if stack`.",
    difficulty: 1,
    tags: ["stack"],
  },

  // ================= Linked List =================
  {
    id: "ll-node-def",
    language: "python",
    topic: "Linked List",
    primitive: "linked list",
    type: "fill",
    prompt: "Complete the singly-linked node initializer.",
    code: "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.___ = next",
    answer: "next",
    explanation: "Each node stores a value and a pointer to the next node.",
    difficulty: 1,
    tags: ["linked-list"],
  },
  {
    id: "ll-reverse-savenext",
    language: "python",
    topic: "Linked List",
    primitive: "linked list",
    type: "fill",
    prompt: "First line of the reverse loop — save the next node before rewiring.",
    code: "nxt = curr.___\ncurr.next = prev",
    answer: "next",
    explanation: "Capture curr.next before overwriting it, or you lose the rest of the list.",
    difficulty: 2,
    tags: ["linked-list"],
  },
  {
    id: "ll-traverse",
    language: "python",
    topic: "Linked List",
    primitive: "linked list",
    type: "mcq",
    prompt: "How do you advance to the next node in a traversal?",
    answer: "a",
    options: [
      { id: "a", text: "curr = curr.next" },
      { id: "b", text: "curr.next()" },
      { id: "c", text: "curr += 1" },
      { id: "d", text: "next(curr)" },
    ],
    explanation: "Reassign curr to curr.next until it becomes None.",
    difficulty: 1,
    tags: ["linked-list"],
  },
  {
    id: "ll-dummy",
    language: "python",
    topic: "Linked List",
    primitive: "linked list",
    type: "mcq",
    prompt: "Why use a dummy head node when building a list?",
    answer: "b",
    options: [
      { id: "a", text: "It saves memory" },
      { id: "b", text: "It avoids special-casing the real head" },
      { id: "c", text: "It sorts the list" },
      { id: "d", text: "It reverses the list" },
    ],
    explanation: "A dummy gives a stable node to attach to; return dummy.next at the end.",
    difficulty: 2,
    tags: ["linked-list"],
  },
  {
    id: "ll-fast-slow",
    language: "python",
    topic: "Linked List",
    primitive: "fast/slow",
    type: "fill",
    prompt: "Advance the fast pointer two steps in Floyd's cycle detection.",
    code: "slow = slow.next\nfast = fast.next.___",
    answer: "next",
    explanation: "fast moves 2×; if it laps slow, there's a cycle.",
    difficulty: 2,
    tags: ["linked-list", "two-pointers"],
  },
  {
    id: "ll-cycle",
    language: "python",
    topic: "Linked List",
    primitive: "fast/slow",
    type: "mcq",
    prompt: "A cycle exists when…",
    answer: "a",
    options: [
      { id: "a", text: "fast == slow at some point" },
      { id: "b", text: "fast reaches None" },
      { id: "c", text: "slow reaches None" },
      { id: "d", text: "the list has > 100 nodes" },
    ],
    explanation: "If fast catches slow, the pointers are on a loop; reaching None means no cycle.",
    difficulty: 2,
    tags: ["linked-list"],
  },

  // ================= Trees =================
  {
    id: "tree-node-def",
    language: "python",
    topic: "Trees",
    primitive: "tree",
    type: "fill",
    prompt: "A binary tree node has a value and two child pointers named…",
    code: "self.val = val\nself.left = left\nself.___ = right",
    answer: "right",
    explanation: "Binary tree nodes carry left and right child references.",
    difficulty: 1,
    tags: ["tree"],
  },
  {
    id: "tree-base-case",
    language: "python",
    topic: "Trees",
    primitive: "DFS",
    type: "fill",
    prompt: "Guard clause at the top of a recursive tree function.",
    code: "if ___ node:\n    return 0",
    answer: "not",
    explanation: "`if not node` handles the empty/leaf-child base case.",
    difficulty: 1,
    tags: ["tree", "dfs"],
  },
  {
    id: "tree-preorder",
    language: "python",
    topic: "Trees",
    primitive: "DFS",
    type: "mcq",
    prompt: "Pre-order traversal visits nodes in what order?",
    answer: "a",
    options: [
      { id: "a", text: "node, left, right" },
      { id: "b", text: "left, node, right" },
      { id: "c", text: "left, right, node" },
      { id: "d", text: "right, left, node" },
    ],
    explanation: "Pre-order processes the current node before its subtrees.",
    difficulty: 2,
    tags: ["dfs", "tree"],
  },
  {
    id: "tree-postorder",
    language: "python",
    topic: "Trees",
    primitive: "DFS",
    type: "mcq",
    prompt: "Which traversal is natural for computing subtree sums/heights bottom-up?",
    answer: "c",
    options: [
      { id: "a", text: "pre-order" },
      { id: "b", text: "in-order" },
      { id: "c", text: "post-order" },
      { id: "d", text: "level-order" },
    ],
    explanation: "Post-order (left, right, node) has both child results ready before the node.",
    difficulty: 2,
    tags: ["dfs", "tree"],
  },
  {
    id: "tree-bfs-deque",
    language: "python",
    topic: "Trees",
    primitive: "BFS",
    type: "fill",
    prompt: "Seed a level-order traversal queue with the root.",
    code: "from collections import deque\nq = ___([root])",
    answer: "deque",
    explanation: "BFS uses a deque; popleft each node and enqueue its children.",
    difficulty: 2,
    tags: ["bfs", "tree"],
  },
  {
    id: "tree-maxdepth",
    language: "python",
    topic: "Trees",
    primitive: "DFS",
    type: "mcq",
    prompt: "Return value for max depth at a node?",
    answer: "a",
    options: [
      { id: "a", text: "1 + max(left, right)" },
      { id: "b", text: "max(left, right)" },
      { id: "c", text: "left + right" },
      { id: "d", text: "1 + left + right" },
    ],
    explanation: "Depth is 1 (this node) plus the taller subtree.",
    difficulty: 2,
    tags: ["dfs", "tree"],
  },

  // ================= Tries =================
  {
    id: "trie-setdefault",
    language: "python",
    topic: "Tries",
    primitive: "trie",
    type: "fill",
    prompt: "Descend/create the child node for char c (nodes are dicts).",
    code: "node = node.___(c, {})",
    answer: "setdefault",
    explanation: "setdefault(c, {}) returns the child, creating an empty dict if missing.",
    difficulty: 2,
    tags: ["trie", "dict"],
  },
  {
    id: "trie-end-marker",
    language: "python",
    topic: "Tries",
    primitive: "trie",
    type: "mcq",
    prompt: "How do you mark that a word ends at a trie node?",
    answer: "b",
    options: [
      { id: "a", text: "node = None" },
      { id: "b", text: "store a sentinel key, e.g. node['#'] = True" },
      { id: "c", text: "node.append(word)" },
      { id: "d", text: "delete the node" },
    ],
    explanation: "A sentinel key (or an is_word flag) distinguishes a full word from a prefix.",
    difficulty: 2,
    tags: ["trie"],
  },
  {
    id: "trie-search-miss",
    language: "python",
    topic: "Tries",
    primitive: "trie",
    type: "mcq",
    prompt: "During search, when do you return False early?",
    answer: "a",
    options: [
      { id: "a", text: "when a char is not in the current node's children" },
      { id: "b", text: "when the word is long" },
      { id: "c", text: "when node is a dict" },
      { id: "d", text: "never" },
    ],
    explanation: "If `c not in node`, that prefix path doesn't exist — return False.",
    difficulty: 2,
    tags: ["trie"],
  },

  // ================= Heap / Priority Queue =================
  {
    id: "heap-tuple-order",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "mcq",
    prompt: "To pop by priority, what do you push onto the heap?",
    answer: "b",
    options: [
      { id: "a", text: "item only" },
      { id: "b", text: "(priority, item) tuples" },
      { id: "c", text: "(item, priority) tuples" },
      { id: "d", text: "a dict" },
    ],
    explanation: "Tuples compare by first element, so priority must come first.",
    difficulty: 2,
    tags: ["heapq"],
  },
  {
    id: "heap-peek",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "fill",
    prompt: "Peek at the smallest heap element without popping.",
    code: "smallest = h[___]",
    answer: "0",
    explanation: "The min is always at index 0 of the heap list.",
    difficulty: 1,
    tags: ["heapq"],
  },
  {
    id: "heap-nlargest",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "fill",
    prompt: "Get the 3 largest numbers from nums in one call.",
    code: "top3 = heapq.___(3, nums)",
    answer: "nlargest",
    explanation: "heapq.nlargest(k, iterable) returns the k biggest items.",
    difficulty: 2,
    tags: ["heapq"],
  },

  // ================= Backtracking =================
  {
    id: "bt-copy-path",
    language: "python",
    topic: "Backtracking",
    primitive: "backtracking",
    type: "fill",
    prompt: "Record the current path as a result (must be a copy).",
    code: "res.append(path[___])",
    answer: ":",
    explanation: "path[:] copies the list; appending path itself would store a live reference.",
    difficulty: 2,
    tags: ["backtracking"],
  },
  {
    id: "bt-undo",
    language: "python",
    topic: "Backtracking",
    primitive: "backtracking",
    type: "fill",
    prompt: "Undo the last choice after recursing.",
    code: "path.append(x)\nbacktrack(...)\npath.___()",
    answer: "pop",
    explanation: "pop() removes the last element, restoring state before the next choice.",
    difficulty: 2,
    tags: ["backtracking"],
  },
  {
    id: "bt-start-index",
    language: "python",
    topic: "Backtracking",
    primitive: "backtracking",
    type: "mcq",
    prompt: "To avoid reusing earlier elements in combinations, recurse with…",
    answer: "b",
    options: [
      { id: "a", text: "backtrack(0)" },
      { id: "b", text: "backtrack(i + 1)" },
      { id: "c", text: "backtrack(i)" },
      { id: "d", text: "backtrack(len(nums))" },
    ],
    explanation: "Passing i+1 as the next start prevents picking the same/earlier indices.",
    difficulty: 3,
    tags: ["backtracking"],
  },
  {
    id: "bt-permutations",
    language: "python",
    topic: "Backtracking",
    primitive: "backtracking",
    type: "mcq",
    prompt: "Permutations differ from combinations because they…",
    answer: "a",
    options: [
      { id: "a", text: "track which elements are used, order matters" },
      { id: "b", text: "use a start index" },
      { id: "c", text: "never copy the path" },
      { id: "d", text: "require sorting" },
    ],
    explanation: "Permutations consider order, so you track a used[] set rather than a start index.",
    difficulty: 3,
    tags: ["backtracking"],
  },

  // ================= Graphs =================
  {
    id: "graph-adj-build",
    language: "python",
    topic: "Graphs",
    primitive: "graph",
    type: "fill",
    prompt: "Build an adjacency list that auto-creates empty neighbor lists.",
    code: "from collections import defaultdict\ngraph = defaultdict(___)",
    answer: "list",
    explanation: "defaultdict(list) lets you graph[u].append(v) without key checks.",
    difficulty: 2,
    tags: ["graph", "defaultdict"],
  },
  {
    id: "graph-dirs",
    language: "python",
    topic: "Graphs",
    primitive: "grid",
    type: "mcq",
    prompt: "Which lists the 4 orthogonal grid moves?",
    answer: "a",
    options: [
      { id: "a", text: "[(0,1),(0,-1),(1,0),(-1,0)]" },
      { id: "b", text: "[(1,1),(-1,-1),(1,-1),(-1,1)]" },
      { id: "c", text: "[(0,0),(1,1)]" },
      { id: "d", text: "range(4)" },
    ],
    explanation: "The four cardinal deltas move right, left, down, up.",
    difficulty: 2,
    tags: ["graph", "grid", "bfs"],
  },
  {
    id: "graph-inbounds",
    language: "python",
    topic: "Graphs",
    primitive: "grid",
    type: "mcq",
    prompt: "Correct in-bounds check for cell (r, c) in an R×C grid?",
    answer: "b",
    options: [
      { id: "a", text: "0 < r < R and 0 < c < C" },
      { id: "b", text: "0 <= r < R and 0 <= c < C" },
      { id: "c", text: "r <= R and c <= C" },
      { id: "d", text: "r in R and c in C" },
    ],
    explanation: "Indices are 0-based: valid range is 0 <= r < R (and same for c).",
    difficulty: 2,
    tags: ["graph", "grid"],
  },
  {
    id: "graph-bfs-visited",
    language: "python",
    topic: "Graphs",
    primitive: "BFS",
    type: "mcq",
    prompt: "To avoid revisiting nodes in BFS, mark visited…",
    answer: "a",
    options: [
      { id: "a", text: "when you enqueue a node" },
      { id: "b", text: "when you dequeue a node" },
      { id: "c", text: "at the very end" },
      { id: "d", text: "never" },
    ],
    explanation: "Marking on enqueue prevents the same node being queued twice.",
    difficulty: 3,
    tags: ["bfs", "graph"],
  },
  {
    id: "graph-dfs-guard",
    language: "python",
    topic: "Graphs",
    primitive: "DFS",
    type: "fill",
    prompt: "First line of a grid DFS: bail on out-of-bounds or already-seen.",
    code: "if r < 0 or r >= R or c < 0 or c >= C or (r, c) ___ seen:\n    return",
    answer: "in",
    explanation: "Stop if the cell is off-grid or already visited.",
    difficulty: 2,
    tags: ["dfs", "graph"],
  },

  // ================= Advanced Graphs =================
  {
    id: "ag-dijkstra-push",
    language: "python",
    topic: "Advanced Graphs",
    primitive: "Dijkstra",
    type: "fill",
    prompt: "Push a neighbor onto Dijkstra's min-heap ordered by distance.",
    code: "heapq.heappush(pq, (dist + w, ___))",
    answer: "nxt",
    explanation: "Entries are (distance, node) so the heap always pops the closest frontier node.",
    difficulty: 3,
    tags: ["dijkstra", "heapq"],
  },
  {
    id: "ag-topo-indegree",
    language: "python",
    topic: "Advanced Graphs",
    primitive: "topological sort",
    type: "mcq",
    prompt: "In Kahn's algorithm you start the queue with nodes whose in-degree is…",
    answer: "a",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "the maximum" },
      { id: "d", text: "equal to their out-degree" },
    ],
    explanation: "Zero in-degree means no prerequisites — safe to process first.",
    difficulty: 3,
    tags: ["topological-sort"],
  },
  {
    id: "ag-uf-find",
    language: "python",
    topic: "Advanced Graphs",
    primitive: "union-find",
    type: "fill",
    prompt: "Path-compressing find: point x directly at its grandparent as you climb.",
    code: "while parent[x] != x:\n    parent[x] = parent[parent[x]]\n    x = parent[___]",
    answer: "x",
    explanation: "Reassigning parent[x] to its grandparent flattens the tree over time.",
    difficulty: 3,
    tags: ["union-find"],
  },
  {
    id: "ag-uf-union",
    language: "python",
    topic: "Advanced Graphs",
    primitive: "union-find",
    type: "mcq",
    prompt: "How do you union sets containing a and b?",
    answer: "a",
    options: [
      { id: "a", text: "parent[find(a)] = find(b)" },
      { id: "b", text: "parent[a] = b" },
      { id: "c", text: "parent[a] = parent[b]" },
      { id: "d", text: "find(a) = find(b)" },
    ],
    explanation: "Attach one set's ROOT under the other's root, not the raw nodes.",
    difficulty: 3,
    tags: ["union-find"],
  },

  // ================= 1-D DP =================
  {
    id: "dp-init-1d",
    language: "python",
    topic: "1-D DP",
    primitive: "dp table",
    type: "fill",
    prompt: "Allocate a 1-D dp array of n+1 zeros.",
    code: "dp = [0] * (n + ___)",
    answer: "1",
    explanation: "n+1 entries let dp[0] be a base case and dp[n] the answer.",
    difficulty: 1,
    tags: ["dp"],
  },
  {
    id: "dp-rolling",
    language: "python",
    topic: "1-D DP",
    primitive: "dp rolling",
    type: "mcq",
    prompt: "House Robber's rolling update `prev, curr = curr, max(curr, prev + x)` saves what?",
    answer: "b",
    options: [
      { id: "a", text: "time only" },
      { id: "b", text: "space — O(1) instead of an O(n) table" },
      { id: "c", text: "nothing" },
      { id: "d", text: "it sorts the input" },
    ],
    explanation: "Only the last two states matter, so two variables replace the whole array.",
    difficulty: 2,
    tags: ["dp"],
  },
  {
    id: "dp-climb",
    language: "python",
    topic: "1-D DP",
    primitive: "dp",
    type: "mcq",
    prompt: "Climbing Stairs recurrence for ways to reach step i?",
    answer: "a",
    options: [
      { id: "a", text: "dp[i] = dp[i-1] + dp[i-2]" },
      { id: "b", text: "dp[i] = dp[i-1] * 2" },
      { id: "c", text: "dp[i] = dp[i-1] + 1" },
      { id: "d", text: "dp[i] = max(dp[i-1], dp[i-2])" },
    ],
    explanation: "You arrive from one or two steps below — a Fibonacci recurrence.",
    difficulty: 2,
    tags: ["dp"],
  },
  {
    id: "dp-coin-init",
    language: "python",
    topic: "1-D DP",
    primitive: "dp",
    type: "fill",
    prompt: "Coin Change: seed the dp array so unreachable amounts stay 'impossible'.",
    code: "dp = [float('___')] * (amount + 1)\ndp[0] = 0",
    answer: "inf",
    explanation: "Infinity marks amounts not yet reachable; dp[0] = 0 coins for amount 0.",
    difficulty: 2,
    tags: ["dp"],
  },

  // ================= 2-D DP =================
  {
    id: "dp2d-init",
    language: "python",
    topic: "2-D DP",
    primitive: "dp grid",
    type: "fill",
    prompt: "Allocate an (m+1)×(n+1) dp grid of zeros without aliasing rows.",
    code: "dp = [[0] * (n + 1) ___ _ in range(m + 1)]",
    answer: "for",
    explanation: "The comprehension builds m+1 independent rows; [[0]*n]*m would share one.",
    difficulty: 2,
    tags: ["dp", "grid"],
  },
  {
    id: "dp2d-lcs",
    language: "python",
    topic: "2-D DP",
    primitive: "dp grid",
    type: "mcq",
    prompt: "LCS: when characters match, dp[i][j] = ?",
    answer: "a",
    options: [
      { id: "a", text: "dp[i-1][j-1] + 1" },
      { id: "b", text: "max(dp[i-1][j], dp[i][j-1])" },
      { id: "c", text: "dp[i-1][j-1]" },
      { id: "d", text: "0" },
    ],
    explanation: "A match extends the diagonal subproblem by one.",
    difficulty: 3,
    tags: ["dp"],
  },
  {
    id: "dp2d-lcs-miss",
    language: "python",
    topic: "2-D DP",
    primitive: "dp grid",
    type: "mcq",
    prompt: "LCS: when characters differ, dp[i][j] = ?",
    answer: "b",
    options: [
      { id: "a", text: "dp[i-1][j-1]" },
      { id: "b", text: "max(dp[i-1][j], dp[i][j-1])" },
      { id: "c", text: "dp[i-1][j] + dp[i][j-1]" },
      { id: "d", text: "0" },
    ],
    explanation: "Drop one character from either string and take the better subproblem.",
    difficulty: 3,
    tags: ["dp"],
  },

  // ================= Greedy =================
  {
    id: "greedy-kadane",
    language: "python",
    topic: "Greedy",
    primitive: "Kadane",
    type: "fill",
    prompt: "Kadane's core step: extend the run or restart at x.",
    code: "cur = ___(x, cur + x)",
    answer: "max",
    explanation: "Take the larger of starting fresh (x) or extending the current sum.",
    difficulty: 2,
    tags: ["greedy", "dp"],
  },
  {
    id: "greedy-jump",
    language: "python",
    topic: "Greedy",
    primitive: "greedy",
    type: "mcq",
    prompt: "Jump Game (can you reach the end) is best solved by tracking…",
    answer: "a",
    options: [
      { id: "a", text: "the farthest index reachable so far" },
      { id: "b", text: "a full dp table only" },
      { id: "c", text: "a stack of jumps" },
      { id: "d", text: "the number of zeros" },
    ],
    explanation: "Greedily keep the max reach; if an index exceeds it, the end is unreachable.",
    difficulty: 2,
    tags: ["greedy"],
  },
  {
    id: "greedy-sort-first",
    language: "python",
    topic: "Greedy",
    primitive: "greedy",
    type: "mcq",
    prompt: "Most interval/greedy scheduling proofs start by…",
    answer: "c",
    options: [
      { id: "a", text: "reversing the input" },
      { id: "b", text: "using recursion" },
      { id: "c", text: "sorting by a key (e.g. end time)" },
      { id: "d", text: "hashing" },
    ],
    explanation: "Sorting by the right key makes the locally optimal choice provably global.",
    difficulty: 2,
    tags: ["greedy", "sorting"],
  },

  // ================= Intervals =================
  {
    id: "int-sort-start",
    language: "python",
    topic: "Intervals",
    primitive: "intervals",
    type: "fill",
    prompt: "Sort intervals by start before merging.",
    code: "intervals.sort(key=lambda x: x[___])",
    answer: "0",
    explanation: "Sorting by start lets you sweep left-to-right and merge overlaps.",
    difficulty: 1,
    tags: ["intervals", "sorting"],
  },
  {
    id: "int-overlap",
    language: "python",
    topic: "Intervals",
    primitive: "intervals",
    type: "mcq",
    prompt: "Sorted by start, interval b overlaps the last merged interval when…",
    answer: "a",
    options: [
      { id: "a", text: "b[0] <= merged[-1][1]" },
      { id: "b", text: "b[0] > merged[-1][1]" },
      { id: "c", text: "b[1] < merged[-1][0]" },
      { id: "d", text: "b[0] == b[1]" },
    ],
    explanation: "If b starts at/before the last end, they overlap and should merge.",
    difficulty: 2,
    tags: ["intervals"],
  },
  {
    id: "int-merge-extend",
    language: "python",
    topic: "Intervals",
    primitive: "intervals",
    type: "fill",
    prompt: "Extend the last merged interval's end to cover the current one.",
    code: "merged[-1][1] = ___(merged[-1][1], end)",
    answer: "max",
    explanation: "The merged end is the larger of the two ends.",
    difficulty: 2,
    tags: ["intervals"],
  },
  {
    id: "int-meeting-rooms",
    language: "python",
    topic: "Intervals",
    primitive: "intervals",
    type: "mcq",
    prompt: "Minimum meeting rooms is elegantly tracked with a…",
    answer: "b",
    options: [
      { id: "a", text: "stack of ends" },
      { id: "b", text: "min-heap of end times" },
      { id: "c", text: "single counter" },
      { id: "d", text: "trie" },
    ],
    explanation: "A min-heap of end times reuses a room when the earliest meeting has ended.",
    difficulty: 3,
    tags: ["intervals", "heapq"],
  },

  // ================= Math & Geometry =================
  {
    id: "math-last-digit",
    language: "python",
    topic: "Math & Geometry",
    primitive: "math",
    type: "fill",
    prompt: "Extract the last decimal digit of n.",
    code: "digit = n ___ 10",
    answer: "%",
    explanation: "n % 10 is the last digit; n //= 10 drops it.",
    difficulty: 1,
    tags: ["math"],
  },
  {
    id: "math-gcd",
    language: "python",
    topic: "Math & Geometry",
    primitive: "math",
    type: "fill",
    prompt: "Greatest common divisor of a and b from the standard library.",
    code: "import math\ng = math.___(a, b)",
    answer: "gcd",
    explanation: "math.gcd(a, b) returns the greatest common divisor.",
    difficulty: 1,
    tags: ["math"],
  },
  {
    id: "math-transpose",
    language: "python",
    topic: "Math & Geometry",
    primitive: "matrix",
    type: "mcq",
    prompt: "Which transposes a matrix (rows become columns)?",
    answer: "b",
    options: [
      { id: "a", text: "matrix[::-1]" },
      { id: "b", text: "list(zip(*matrix))" },
      { id: "c", text: "matrix.T" },
      { id: "d", text: "reversed(matrix)" },
    ],
    explanation: "zip(*matrix) pairs up the i-th element of each row — a transpose.",
    difficulty: 2,
    tags: ["matrix"],
  },
  {
    id: "math-parse-base",
    language: "python",
    topic: "Math & Geometry",
    primitive: "int()",
    type: "mcq",
    prompt: "What does int('1010', 2) return?",
    answer: "a",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "1010" },
      { id: "c", text: "'1010'" },
      { id: "d", text: "5" },
    ],
    explanation: "int(s, base) parses s in the given base; binary 1010 is 10.",
    difficulty: 2,
    tags: ["math"],
  },

  // ================= Bit Manipulation =================
  {
    id: "bit-shift-mask",
    language: "python",
    topic: "Bit Manipulation",
    primitive: "bit ops",
    type: "fill",
    prompt: "Build a mask with only bit i set.",
    code: "mask = 1 ___ i",
    answer: "<<",
    explanation: "1 << i shifts a single set bit into position i.",
    difficulty: 1,
    tags: ["bit-manipulation"],
  },
  {
    id: "bit-clear-lowest",
    language: "python",
    topic: "Bit Manipulation",
    primitive: "bit ops",
    type: "mcq",
    prompt: "What does n & (n - 1) do?",
    answer: "a",
    options: [
      { id: "a", text: "clears the lowest set bit" },
      { id: "b", text: "isolates the lowest set bit" },
      { id: "c", text: "sets the lowest bit" },
      { id: "d", text: "reverses all bits" },
    ],
    explanation: "n & (n-1) drops the least-significant 1 — the basis of Brian Kernighan's count.",
    difficulty: 3,
    tags: ["bit-manipulation"],
  },
  {
    id: "bit-test",
    language: "python",
    topic: "Bit Manipulation",
    primitive: "bit ops",
    type: "fill",
    prompt: "Test whether bit i of n is set (non-zero if so).",
    code: "if n & (1 ___ i):\n    ...",
    answer: "<<",
    explanation: "n & (1 << i) is non-zero exactly when bit i is set.",
    difficulty: 2,
    tags: ["bit-manipulation"],
  },
  {
    id: "bit-xor-pairs",
    language: "python",
    topic: "Bit Manipulation",
    primitive: "XOR",
    type: "mcq",
    prompt: "XOR-ing all elements where every value appears twice except one yields…",
    answer: "a",
    options: [
      { id: "a", text: "the single unpaired value" },
      { id: "b", text: "0 always" },
      { id: "c", text: "the sum" },
      { id: "d", text: "the maximum" },
    ],
    explanation: "x ^ x == 0, so paired values cancel and only the loner remains.",
    difficulty: 2,
    tags: ["bit-manipulation"],
  },

  // ================= Binary Search (more) =================
  {
    id: "bs-while-cond",
    language: "python",
    topic: "Binary Search",
    primitive: "binary search",
    type: "fill",
    prompt: "Standard inclusive binary-search loop condition.",
    code: "while lo ___ hi:",
    answer: "<=",
    explanation: "With hi as a valid index, use lo <= hi so the last element is checked.",
    difficulty: 2,
    tags: ["binary-search"],
  },
  {
    id: "bs-update",
    language: "python",
    topic: "Binary Search",
    primitive: "binary search",
    type: "mcq",
    prompt: "Target is greater than a[mid]. Update?",
    answer: "a",
    options: [
      { id: "a", text: "lo = mid + 1" },
      { id: "b", text: "hi = mid - 1" },
      { id: "c", text: "lo = mid" },
      { id: "d", text: "hi = mid" },
    ],
    explanation: "The answer is to the right, so discard mid and everything left: lo = mid + 1.",
    difficulty: 2,
    tags: ["binary-search"],
  },
  {
    id: "bs-answer-space",
    language: "python",
    topic: "Binary Search",
    primitive: "binary search",
    type: "mcq",
    prompt: "Koko Eating Bananas binary-searches over…",
    answer: "b",
    options: [
      { id: "a", text: "the array of piles" },
      { id: "b", text: "the possible eating speeds (answer space)" },
      { id: "c", text: "the hours" },
      { id: "d", text: "prime numbers" },
    ],
    explanation: "You search the monotonic answer space (speed), not the input array.",
    difficulty: 3,
    tags: ["binary-search"],
  },

  // ================= Sorting / comprehensions (more) =================
  {
    id: "sort-multi-key",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "sorted key",
    type: "mcq",
    prompt: "Sort by length ascending, then alphabetically. key = ?",
    answer: "a",
    options: [
      { id: "a", text: "lambda w: (len(w), w)" },
      { id: "b", text: "lambda w: len(w) + w" },
      { id: "c", text: "lambda w: w, len(w)" },
      { id: "d", text: "len, str" },
    ],
    explanation: "A tuple key sorts by the first element, then breaks ties by the second.",
    difficulty: 2,
    tags: ["sorting", "lambda"],
  },
  {
    id: "comp-flatten",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "comprehensions",
    type: "fill",
    prompt: "Flatten a 2-D grid into a single list.",
    code: "flat = [x for row in grid ___ x in row]",
    answer: "for",
    explanation: "Nested comprehension loops read left-to-right: outer `for row`, inner `for x`.",
    difficulty: 2,
    tags: ["comprehensions"],
  },
  {
    id: "comp-generator",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "comprehensions",
    type: "mcq",
    prompt: "What does (x*x for x in nums) create?",
    answer: "b",
    options: [
      { id: "a", text: "a list" },
      { id: "b", text: "a lazy generator" },
      { id: "c", text: "a set" },
      { id: "d", text: "a tuple" },
    ],
    explanation: "Parentheses make a generator — values are produced lazily, saving memory.",
    difficulty: 2,
    tags: ["comprehensions", "generator"],
  },

  // ================= collections / deque (more) =================
  {
    id: "deque-maxlen",
    language: "python",
    topic: "Sliding Window",
    primitive: "deque",
    type: "mcq",
    prompt: "deque(maxlen=3) behaves how when you append a 4th item?",
    answer: "a",
    options: [
      { id: "a", text: "drops the oldest item from the left" },
      { id: "b", text: "raises an error" },
      { id: "c", text: "ignores the new item" },
      { id: "d", text: "grows to length 4" },
    ],
    explanation: "A bounded deque evicts from the opposite end — a handy ring buffer.",
    difficulty: 2,
    tags: ["deque"],
  },
  {
    id: "counter-arithmetic",
    language: "python",
    topic: "Arrays & Hashing",
    primitive: "Counter",
    type: "mcq",
    prompt: "Counter(a) == Counter(b) checks that a and b…",
    answer: "a",
    options: [
      { id: "a", text: "are anagrams (same multiset of elements)" },
      { id: "b", text: "are identical order" },
      { id: "c", text: "have the same length only" },
      { id: "d", text: "are sorted" },
    ],
    explanation: "Two Counters are equal iff every element has the same count — an anagram test.",
    difficulty: 2,
    tags: ["Counter"],
  },

  // ================= Extra depth on thinner topics =================
  {
    id: "tries-prefix-walk",
    language: "python",
    topic: "Tries",
    primitive: "trie",
    type: "fill",
    prompt: "startsWith: bail early if char c isn't a child of the current node.",
    code: "for c in prefix:\n    if c ___ node:\n        return False\n    node = node[c]",
    answer: "not in",
    explanation: "If any prefix char is missing, the prefix path doesn't exist.",
    difficulty: 2,
    tags: ["trie"],
  },
  {
    id: "tries-vs-hash",
    language: "python",
    topic: "Tries",
    primitive: "trie",
    type: "mcq",
    prompt: "A trie beats a hash set when you need to…",
    answer: "a",
    options: [
      { id: "a", text: "query by prefix efficiently" },
      { id: "b", text: "store integers" },
      { id: "c", text: "sort numbers" },
      { id: "d", text: "detect cycles" },
    ],
    explanation: "Tries share prefixes, making prefix and autocomplete queries fast.",
    difficulty: 2,
    tags: ["trie"],
  },
  {
    id: "greedy-return-none",
    language: "python",
    topic: "Greedy",
    primitive: "greedy",
    type: "mcq",
    prompt: "Gas Station: if total gas < total cost, the answer is…",
    answer: "b",
    options: [
      { id: "a", text: "always 0" },
      { id: "b", text: "-1 (impossible)" },
      { id: "c", text: "the last index" },
      { id: "d", text: "the max station" },
    ],
    explanation: "If you burn more than you carry overall, no start completes the loop.",
    difficulty: 2,
    tags: ["greedy"],
  },
  {
    id: "greedy-hand-straights",
    language: "python",
    topic: "Greedy",
    primitive: "greedy",
    type: "mcq",
    prompt: "Grouping consecutive cards greedily is easiest after…",
    answer: "a",
    options: [
      { id: "a", text: "counting with a Counter and sorting the keys" },
      { id: "b", text: "reversing the hand" },
      { id: "c", text: "using a stack" },
      { id: "d", text: "a trie" },
    ],
    explanation: "Count cards, then repeatedly consume runs starting from the smallest key.",
    difficulty: 3,
    tags: ["greedy", "Counter"],
  },
  {
    id: "bt-nqueens-diag",
    language: "python",
    topic: "Backtracking",
    primitive: "backtracking",
    type: "mcq",
    prompt: "N-Queens: cells on the same ↘ diagonal share which invariant?",
    answer: "a",
    options: [
      { id: "a", text: "row - col is constant" },
      { id: "b", text: "row + col is constant" },
      { id: "c", text: "row * col is constant" },
      { id: "d", text: "row == col always" },
    ],
    explanation: "row - col identifies ↘ diagonals; row + col identifies ↙ diagonals.",
    difficulty: 3,
    tags: ["backtracking"],
  },
  {
    id: "bt-subsets-count",
    language: "python",
    topic: "Backtracking",
    primitive: "backtracking",
    type: "mcq",
    prompt: "How many subsets does a set of n distinct elements have?",
    answer: "b",
    options: [
      { id: "a", text: "n" },
      { id: "b", text: "2**n" },
      { id: "c", text: "n!" },
      { id: "d", text: "n**2" },
    ],
    explanation: "Each element is in or out → 2^n subsets.",
    difficulty: 2,
    tags: ["backtracking"],
  },
  {
    id: "dp2d-unique-paths",
    language: "python",
    topic: "2-D DP",
    primitive: "dp grid",
    type: "mcq",
    prompt: "Unique Paths transition for grid cell (i, j)?",
    answer: "a",
    options: [
      { id: "a", text: "dp[i][j] = dp[i-1][j] + dp[i][j-1]" },
      { id: "b", text: "dp[i][j] = dp[i-1][j-1] + 1" },
      { id: "c", text: "dp[i][j] = max(dp[i-1][j], dp[i][j-1])" },
      { id: "d", text: "dp[i][j] = dp[i-1][j] * dp[i][j-1]" },
    ],
    explanation: "You reach a cell from above or from the left, so sum those path counts.",
    difficulty: 2,
    tags: ["dp"],
  },
  {
    id: "dp2d-knapsack-bool",
    language: "python",
    topic: "2-D DP",
    primitive: "dp grid",
    type: "fill",
    prompt: "0/1 subset-sum: either skip item i or take it (reduce the target by its value).",
    code: "dp[i][t] = dp[i-1][t] or dp[i-1][t - ___]",
    answer: "nums[i]",
    explanation: "Skip keeps the same target; take subtracts the item's value from t.",
    difficulty: 3,
    tags: ["dp"],
  },
  {
    id: "ag-dijkstra-skip",
    language: "python",
    topic: "Advanced Graphs",
    primitive: "Dijkstra",
    type: "mcq",
    prompt: "When popping (d, node) from Dijkstra's heap, you skip it if…",
    answer: "a",
    options: [
      { id: "a", text: "d > best known dist[node] (stale entry)" },
      { id: "b", text: "the node is the source" },
      { id: "c", text: "the heap is large" },
      { id: "d", text: "d is even" },
    ],
    explanation: "Lazy deletion: a popped distance worse than the recorded best is outdated.",
    difficulty: 3,
    tags: ["dijkstra"],
  },
  {
    id: "ag-topo-cycle",
    language: "python",
    topic: "Advanced Graphs",
    primitive: "topological sort",
    type: "mcq",
    prompt: "Kahn's algorithm detects a cycle when…",
    answer: "b",
    options: [
      { id: "a", text: "the queue is empty at the start" },
      { id: "b", text: "fewer than n nodes get processed" },
      { id: "c", text: "the graph is a tree" },
      { id: "d", text: "in-degrees are all 1" },
    ],
    explanation: "A cycle leaves some nodes with in-degree > 0 forever, so the order is short.",
    difficulty: 3,
    tags: ["topological-sort"],
  },
  {
    id: "stack-rpn",
    language: "python",
    topic: "Stack",
    primitive: "stack",
    type: "mcq",
    prompt: "Evaluating Reverse Polish Notation, on hitting an operator you…",
    answer: "a",
    options: [
      { id: "a", text: "pop two operands, apply, push the result" },
      { id: "b", text: "push the operator" },
      { id: "c", text: "clear the stack" },
      { id: "d", text: "reverse the stack" },
    ],
    explanation: "Operators consume the top two values; the final stack holds the answer.",
    difficulty: 2,
    tags: ["stack"],
  },
  {
    id: "bs-rotated-half",
    language: "python",
    topic: "Binary Search",
    primitive: "binary search",
    type: "mcq",
    prompt: "In a rotated sorted array, at each step you first determine…",
    answer: "a",
    options: [
      { id: "a", text: "which half (left or right of mid) is sorted" },
      { id: "b", text: "the array length" },
      { id: "c", text: "the median" },
      { id: "d", text: "the rotation count via sorting" },
    ],
    explanation: "One half is always sorted; check if the target lies within it to pick a side.",
    difficulty: 3,
    tags: ["binary-search"],
  },
  {
    id: "sw-best-update",
    language: "python",
    topic: "Sliding Window",
    primitive: "sliding window",
    type: "fill",
    prompt: "Track the longest valid window seen so far.",
    code: "best = ___(best, right - left + 1)",
    answer: "max",
    explanation: "After each valid window, keep the maximum length.",
    difficulty: 1,
    tags: ["sliding-window"],
  },
  {
    id: "int-non-overlap",
    language: "python",
    topic: "Intervals",
    primitive: "intervals",
    type: "mcq",
    prompt: "To remove the fewest intervals so none overlap, greedily keep the one with the…",
    answer: "a",
    options: [
      { id: "a", text: "earliest end time" },
      { id: "b", text: "latest start time" },
      { id: "c", text: "largest range" },
      { id: "d", text: "smallest index" },
    ],
    explanation: "Sorting by end and keeping earliest-ending intervals leaves the most room.",
    difficulty: 3,
    tags: ["intervals", "greedy"],
  },
  {
    id: "heap-kth-largest",
    language: "python",
    topic: "Heap / Priority Queue",
    primitive: "heapq",
    type: "mcq",
    prompt: "To keep the k largest elements in a stream, maintain a…",
    answer: "a",
    options: [
      { id: "a", text: "min-heap of size k" },
      { id: "b", text: "max-heap of size k" },
      { id: "c", text: "sorted list, re-sorted each insert" },
      { id: "d", text: "stack" },
    ],
    explanation: "A size-k min-heap keeps the k biggest; its root is the kth largest.",
    difficulty: 3,
    tags: ["heapq"],
  },
];

export const CARDS: Card[] = [...STARTER, ...MORE];

const BY_ID = new Map(CARDS.map((c) => [c.id, c]));
export function cardById(id: string): Card | undefined {
  return BY_ID.get(id);
}
